#!/bin/bash

gem install spreadsheet

bash ./redmine-plugin-installer

###############################################
# setup plugins
###############################################

pushd .

cd $INSTALL_DIR
rake db:migrate_plugins RAILS_ENV=production 

popd
