#!/bin/bash

gem install spreadsheet

bash ./redmine-plugin-installer

###############################################
# MS Project Import
###############################################
git clone https://github.com/suer/redmine_ms_projects.git $INSTALL_DIR/vendor/plugins/redmine_ms_projects

###############################################
# setup plugins
###############################################

pushd .

cd $INSTALL_DIR
rake db:migrate_plugins RAILS_ENV=production 

popd
