#!/bin/sh

DIR_NAME=(`awk -F, '{print $1}'< config/redmine-plugins.txt `)
DEST_NAME=(`awk -F, '{print $2}'< config/redmine-plugins.txt `)
URL_NAME=(`awk -F, '{print $3}'< config/redmine-plugins.txt `)

for (( i = 0; i < ${#DIR_NAME[@]}; ++i ))
do
  FILE_NAME=`echo ${URL_NAME[$i]} | sed -e "s/.*\/\(.*$\)/\1/"`
  EXT=`echo ${URL_NAME[$i]} | sed -e "s/.*\.\(.*$\)/\1/"`
  echo $EXT
  echo wget ${URL_NAME[$i]}
    case $EXT in 
    zip)
       yes | echo  unzip $FILE_NAME
        ;;

    tgz|gz)
       echo tar zxvf $FILE_NAME
        ;;
    *)
        ;;
    esac
  echo rm -fr $INSTALL_DIR/vendor/plugins/${DIR_NAME[$i]}
  echo mv ${DIR_NAME[$i]} $INSTALL_DIR/vendor/plugins/${DEST_NAME[$i]}
  echo rm -f $FILE_NAME
done
