#!/bin/bash

mysql railsgun -e "drop database railsgun" 
rm -fr /opt/railsgun /var/opt/railsgun
rm -fr /etc/apache2/sites-available/vcs
rm -fr /etc/apache2/sites-available/redmine
rm -fr /etc/apache2/sites-enabled/vcs
rm -fr /etc/apache2/sites-enabled/redmine
rm -fr /etc/httpd/conf.d/redmine.conf
rm -fr /etc/httpd/conf.d/vcs.conf
