#!/bin/bash

mysql railsgun -e "drop database railsgun" 
rm -fr /opt/railsgun /var/opt/railsgun
rm -fr /etc/apache2/sites-available/vcs
rm -fr /etc/apache2/sites-available/railsgun
rm -fr /etc/apache2/sites-enabled/vcs
rm -fr /etc/apache2/sites-enabled/railsgun
