#!/bin/bash
############################################################
# Smart installer for redmine/chiliproject.
############################################################

export RAILS_ENV=production
export INSTALL_DIR=/opt/railsgun
CP_VER=1.5.0
CP_ARC=https://www.chiliproject.org/attachments/download/129/chiliproject-1.5.0.tar.gz
RM_VER=1.2.1
RM_ARC=http://rubyforge.org/frs/download.php/75097/redmine-1.2.1.tar.gz



if [ -f /etc/redhat-release ]
then
    APACHE_USER=apache
    CHK=`egrep "CentOS release 5|Red Hat Enterprise Linux .* 5" /etc/redhat-release`
    if [ "$CHK" != '' ]
    then
#        OS='rhel5'
#        echo "RHEL 5.x / CentOS 5.x / OEL 5.xが検出されました。"
        echo 

    else
        OS='rhel6'
        echo "RHEL 6.x / CentOS 6.x / OEL 6.xが検出されました。"        
    fi
#elif [ -f /etc/debian_version ]
#then
#    OS='debian'
#    APACHE_USER=www-data
#    echo "Debian / Ubuntu が検出されました。"
else
    echo "サポートされていないOSです。"
    echo "現在サポートされいているOSは、"
    echo ""
 #   echo "  * Ubuntu 10.10 Server"
 #   echo "  * Debian GNU/Linux 6.0"
    echo "  * RHEL/Oracle EL/CentOS/SL 6.0/6.1"
    echo ""
    echo "です。"
    exit
fi


if [ "$USER" != 'root' ]
then
    echo "rootでコマンドを実行してください。"
fi



echo "*******************************************************"
echo "  ホスト名の設定"
echo "*******************************************************"
echo "ホスト名(IPアドレスもしくはDNS名)を入力してください。ホスト名はApacheのバーチャルホストで利用されます。"
echo "例えば、192.168.1.4をホスト名で入力すると、http://192.168.1.4/でアクセスすることになります。"
echo "(上記の設定ではhttp://localhost/では接続できないのでご注意ください)"
echo -n "ホスト名: "
read HOSTNAME
echo ""
echo ""

#if [ $TYPE = "" ]
#then
#    echo "redmine もしくは chiliprojectを選択してください。"
#    echo 
#    echo " 1. chiliproject"
#    echo " 2. redmine"
#    echo 
#    echo -n "番号を入力してください: "
#
#    read TYPE
#fi
TYPE=2

case $TYPE in
    1|chiliproject)
        TYPE=chiliproject
        ;;

    2|redmine)
        TYPE=redmine	
        ;;
    *)
        echo "未定義のケットシステムが選択されました。"
        echo "1もしくは2を入力してください。"
        exit 1
        ;;
esac


## install packages
source inst-script/$OS/pre-install

source inst-script/gems

/etc/init.d/mysql start

mysql < config/createdb.sql 

# install chiliproject
mkdir -p $INSTALL_DIR

if [ $TYPE = "chiliproject" ]
then
  if [ ! -f chiliproject-$CP_VER.tar.gz ]
  then
    wget $CP_ARC
  fi
  tar zxf chiliproject-$CP_VER.tar.gz
  cp -fr chiliproject-$CP_VER/* $INSTALL_DIR/
  rm -fr chiliproject-$CP_VER
fi
if [ $TYPE = "redmine" ]
then

  if [ ! -f redmine-$RM_VER.tar.gz ]
  then
    wget $RM_ARC
  fi
  tar zxf redmine-$RM_VER.tar.gz
  
#  (cd redmine-$RM_VER; patch -p1 -R < ../patch/redmine_disable_saltpassword.patch)

  cp -fr redmine-$RM_VER/* $INSTALL_DIR/
  rm -fr redmine-$RM_VER
fi

cp config/database.yml $INSTALL_DIR/config/
cp -r theme/* $INSTALL_DIR/public/themes/
mkdir -p /usr/local/share/perl5/Apache/Authn/

if [ ! -f /usr/local/share/perl5/Apache/Authn/Redmine.pm ]
then
  cp config/Redmine.pm /usr/local/share/perl5/Apache/Authn/
fi

# setup
pushd . 
cd $INSTALL_DIR
rake generate_session_store
rake db:migrate
echo "ja" |RAILS_ENV=production rake redmine:load_default_data

popd

# Customize
mysql railsgun < config/init.mysql
# sqlite3 $INSTALL_DIR/db/railsgun.sqlite < config/init.mysql

# install plugins
source inst-script/redmine-plugins

mkdir -p /etc/opt/railsgun
cp -fr etc/* /etc/opt/railsgun/

mkdir -p $INSTALL_DIR/bin
mkdir -p /var/opt/railsgun/git /var/opt/railsgun/svn
cp -fr bin/*  $INSTALL_DIR/bin/
cp -fr hooks $INSTALL_DIR/

source inst-script/$OS/post-install
