#!/bin/bash

# インストールするディレクトリ名
DEST_NAME=(`grep -v "^#" config/redmine-plugins.txt | awk -F, '{print $1}'`)

# 展開したアーカイブのディレクトリ名 or タグ名
DIR_NAME=(`grep -v "^#" config/redmine-plugins.txt | awk -F, '{print $2}'`)

# URL
URL_NAME=(`grep -v "^#" config/redmine-plugins.txt | awk -F, '{print $3}'`)

for (( i = 0; i < ${#DIR_NAME[@]}; ++i ))
do
  FILE_NAME=`echo ${URL_NAME[$i]} | sed -e "s/.*\/\(.*$\)/\1/"`
  EXT=`echo ${URL_NAME[$i]} | sed -e "s/.*\.\(.*$\)/\1/"`
    case $EXT in 
    zip)
        wget ${URL_NAME[$i]}
        yes | unzip $FILE_NAME
        rm -fr $INSTALL_DIR/vendor/plugins/${DIR_NAME[$i]}
        mv ${DIR_NAME[$i]} $INSTALL_DIR/vendor/plugins/${DEST_NAME[$i]}
        rm -f $FILE_NAME
        ;;

    tgz|gz)
        wget ${URL_NAME[$i]}
        tar zxvf $FILE_NAME
        rm -fr $INSTALL_DIR/vendor/plugins/${DIR_NAME[$i]}
        mv ${DIR_NAME[$i]} $INSTALL_DIR/vendor/plugins/${DEST_NAME[$i]}
        rm -f $FILE_NAME
        ;;
    git)
        git clone ${URL_NAME[$i]}
        cd ${DEST_NAME[$i]}
        git checkout ${DIR_NAME[$i]}
        cd ..
        mv ${DEST_NAME[$i]} $INSTALL_DIR/vendor/plugins/
        ;;
    *)
        ;;
    esac
done
