#!/bin/bash

# インストールするディレクトリ名
DEST_NAME=(`grep -v "^#" config/redmine-plugins.lst | awk -F, '{print $1}'`)

# 展開したアーカイブのディレクトリ名 or タグ名
DIR_NAME=(`grep -v "^#" config/redmine-plugins.lst | awk -F, '{print $2}'`)

# URL
URL_NAME=(`grep -v "^#" config/redmine-plugins.lst | awk -F, '{print $3}'`)

for (( i = 0; i < ${#DIR_NAME[@]}; ++i ))
do
  FILE_NAME=`echo ${URL_NAME[$i]} | sed -e "s/.*\/\(.*$\)/\1/"`
  EXT=`echo ${URL_NAME[$i]} | sed -e "s/.*\.\(.*$\)/\1/"`
    case $EXT in 
    zip)
        if [ ! -f cache/$FILE_NAME ]
        then
          wget -P cache ${URL_NAME[$i]}
        fi
        yes | unzip cache/$FILE_NAME
        rm -fr $INSTALL_DIR/vendor/plugins/${DEST_NAME[$i]}
        mv ${DIR_NAME[$i]} $INSTALL_DIR/vendor/plugins/${DEST_NAME[$i]}
        rm -f $FILE_NAME
        ;;

    tgz|gz)
        if [ ! -f cache/$FILE_NAME ]
        then
          wget -P cache ${URL_NAME[$i]}
        fi
        tar zxf cache/$FILE_NAME
        rm -fr $INSTALL_DIR/vendor/plugins/${DEST_NAME[$i]}
        mv ${DIR_NAME[$i]} $INSTALL_DIR/vendor/plugins/${DEST_NAME[$i]}
        rm -f $FILE_NAME
        ;;
    git)
        if [ ! -f cache/$FILE_NAME ]
        then
          git clone ${URL_NAME[$i]} cache/${DEST_NAME[$i]}
        fi
        cd cache/${DEST_NAME[$i]}
        git checkout ${DIR_NAME[$i]}
        cd ../..
        rm -fr $INSTALL_DIR/vendor/plugins/${DEST_NAME[$i]}        
        cp -ar cache/${DEST_NAME[$i]} $INSTALL_DIR/vendor/plugins/
        ;;
    *)
        ;;
    esac
done


## setup plugin
pushd .

cd $INSTALL_DIR

rake db:migrate_plugins
rake generate_session_store
rake config/initializers/session_store.rb
rake db:migrate
rake db:migrate:upgrade_plugin_migrations
rake tmp:cache:clear
rake tmp:sessions:clear
rake redmine:backlogs:install task_tracker=4 story_trackers=2 labels=false
popd
