#!/bin/bash

if [ ! -f /etc/httpd/conf.d/railsgun.conf ]
then
  PASSENGER_VERSION=`passenger-config  --version`
  sed 's/%HOSTNAME%/'$HOSTNAME'/' config/httpd.conf | \
      sed 's/%PASSENGER_VERSION%/'$PASSENGER_VERSION'/' > /etc/httpd/conf.d/railsgun.conf
  sed 's/%HOSTNAME%/'$HOSTNAME'/' config/httpd-vcs.conf > /etc/httpd/conf.d/vcs.conf     
fi
          
# セキュリティ無効化の設定        
if [ ! "$USE_DISABLE_SECURITY" = "n" ]
then
  # SELinuxを無効化
  echo 0 > /selinux/enforce
  CHK=`grep SELINUX=enforcing /etc/selinux/config`
  if [ ! "$CHK" = '' ]                            
  then                
    cat /etc/selinux/config |sed 's/SELINUX=enforcing/SELINUX=disabled/' > /tmp/selinux_config
    mv /tmp/selinux_config /etc/selinux/config                                                
    echo "SELinuxが無効化されました"          
  fi
              
  # ファイアウォールの設定で80番(http)を許可
  CHK=`grep "dport 80" /etc/sysconfig/iptables`
  if [ "$CHK" = '' ]                           
  then              
    RULENUM=`iptables-save |grep INPUT |grep -n "dport 22"|awk -F : '{print $1}'`
    iptables -I  INPUT ${RULENUM} -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
    iptables-save > /etc/sysconfig/iptables
    echo "tcp 80番ポートのアクセスを許可しました"
  fi                                               
fi
    
chkconfig --add httpd
chkconfig httpd on
service httpd stop
service httpd start
