#!/bin/bash

if [ ! -f /etc/apache2/sites-available/redmine ]
then
  sed 's/%HOSTNAME%/'$HOSTNAME'/' inst-script/debian/httpd-redmine.conf > /etc/apache2/sites-available/redmine
  sed 's/%HOSTNAME%/'$HOSTNAME'/' inst-script/debian/httpd-vcs.conf > /etc/apache2/sites-available/vcs
fi

a2enmod expires
a2enmod dav_fs
a2enmod auth_mysql
a2ensite redmine
a2ensite vcs

service apache2 stop
service apache2 start